### ISSUE TITLE
Suggestion: Migrate Notifications Table

### ISSUE THREAD

**Issue by rtd62** [YABhq/Laracogs#155]
Just a small note/suggestion, in the docs you should mention to run `php artisan migrate` after running the cog for notifications, otherwise, an exception will be thrown. Many thanks! Love the package so far! 🍻

**Comment by mlantz** [comment]
Good call @rtd62 will do! Maybe its time to do some general doc updates all around :)

**Comment by rtd62** [comment]
If you need help @mlantz - then I am willing to contribute. I understand how large the project is 😄

**Comment by mlantz** [comment]
PRs are always welcome :)

**Comment by Friss07** [comment]
Hello there,
I just wanted to point out a little difficulty I am currently facing to.
When I go to myapp.dev/admin/notifications, I get a fatal error exception caused by line 34 of the index.blade, **Notifications class is not found**.

`Notifications::getUser($notification->user_id)->name`
the line in charge of grabbing the name of the user having the notification.

When I try to add to the aliases array of the config/app.php file, this line
`'Notifications' => App\Facades\Notifications::class,`
and then reload the index view, I get another exception, with the following message,

**Class NotificationService does not exist** 

I post here, because, **before** following the advices of @rtd62, when I went to 
myapp.dev/admin/notifications, I just got only the dashboard content, nothing else, just as if nothing has happened.

Do you have any ideas regarding my problem?
Note that I do not experience this issue if I put a @yield('content') at the end of the dashboard view file, but this not what I am willing to do :) So I suppose that I must be wrong using namespace maybe?? but after more than 2hours... I am asking for help.

Anyways laracogs looks great and I really would like to resolve this in order to be able to use it for my next project.
Thank you.
