### ISSUE TITLE
When added to team, it doesn't show up in the team.

### ISSUE THREAD

**Issue by MatthewSH** [YABhq/Laracogs#29]
When I add a new user to the team and I go to that user, it doesn't actually show the team in the teams page.

**Comment by mlantz** [comment]
You mean when you login as that user? Its because the teams are listed as teams you own. That user is a member of the team, but since I have no idea if you want them to have admin access to the team or anything like that I didn't want to make many more assumptions. You could easily add in methods in the TeamController and service that would let a team member view teams they are a member of :)
