### ISSUE TITLE
Modify or set field values in columns config?

### ISSUE THREAD

**Issue by studiovlijmscherp** [YABhq/Laracogs#94]
How would/can someone modify/set input values by using @form_maker_object?
I need to run some of the values through a date Helper::

Form is created by using @form_maker_object($member, $columns)

my $columns:

```
$columns = [
  'date' => [
     'alt_name' => 'My date',
  ],
```

Would need someting like:
```
$columns = [
  'date' => [
     'alt_name' => 'My date',
     'value' => Helper::toRealdate($value),
  ],
```

**Comment by mlantz** [comment]
You could make a service which prepares your columns and then passes them to the controller. This way you avoid the config file and can use any methods you need to help prepare your columns.

**Comment by studiovlijmscherp** [comment]
Thanks, but creating te columns isn't the problem. How can I set the value for a column - as in the value of the input field.

Get Outlook for iOS




On Thu, Oct 20, 2016 at 6:26 AM +0200, "Matt Lantz" <notifications@github.com> wrote:












You could make a service which prepares your columns and then passes them to the controller. This way you avoid the config file and can use any methods you need to help prepare your columns.

**Comment by mlantz** [comment]
Hmmm, you cant technically, the form maker looks at the columns, or the table and then creates the inputs available for it, and then on a failed request it will refill the inputs with the original values. In the case you're describing above it appears the best way is to have a getDateAttribute which would output a string, or whatever your helper is doing.

**Comment by studiovlijmscherp** [comment]
Can you give me a small example of what you're describing? Don't think I get wat you mean.

**Comment by mlantz** [comment]
Example:

```
class Member extends Model {

    function getDateAttribute($value)
    {
        return Helper::doSomething($value);
    }

}
```

```
$columns = [
  'date' => [
     'alt_name' => 'My date',
  ],
];

@form_maker_object($member, $columns)
```

Since the form maker is building itself from the object in this case its looking at the object's attributes, this means you can set them in the Model or object itself. In this case it looks at the column 'date' and says ok lets see if there is an attribute/property called date for this object ($member) if there is good, and if the date is also not a method then lets get this attribute from the object. So in this case it would try $member->date with Laravel we can do getDateAttribute which says to the form maker, instead of getting that one take this one. so you can do you're custom magic in there.
